### ENV
#
# REDIRECT_DESTINATION
# REDIRECT_SOURCE
# 
version: '3.8'

services:

  sites-2-ligerosmart-com:
    image: morbz/docker-web-redirect
    environment:
      - REDIRECT_TARGET=${REDIRECT_DESTINATION}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:${REDIRECT_SOURCE}
      - traefik.protocol=http
      - traefik.docker.network=web
    networks:
      - web
      
      
networks:
  web:
    external: true
